version: 10.2.2.{build}
build_script:
- ps: >-
    New-Item -ItemType Directory -Force -Path .\dist

    .\nuget.exe pack .\src\JetBrains.Annotations.Portable.nuspec -OutputDirectory .\dist
artifacts:
- path: ./dist/*.nupkg
  name: nugetOutput
deploy:
- provider: NuGet
  api_key:
    secure: Zwtvv2DPt/sjq5KFgwleojPPiZBNeqZv+vQJ9YN1/C4ltcSOLAbIfSbgYIEka0JZ
  skip_symbols: true
  on:
    branch: master